version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ~/resources/images/:/usr/src/java-app/resources/images/


  web:
    image: nginx:1.17.5-alpine
    restart: always
    volumes:
#      - ~/magellan-ui/dist/magellan:/public_html
      - ./public_html/magellan:/public_html
      - ./conf.d_prod:/etc/nginx/conf.d/
    ports:
      - 80:80


  recommender:
    build:
      context: ../python-recommender
      dockerfile: Dockerfile
    expose:
      - "5000"







#  design:
#    build:
#      context: ../dpp_designgen
#      dockerfile: Dockerfile.designTest
#    expose:
#      - "5000"

#      - ~/resources/images/:/public_html/assets/img2/


#  admin:
#    build:
#      context: ../admin_panel
#      dockerfile: Dockerfile
#    ports:
#      - 4000:80
#    depends_on:
#      - api


#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: PYya8XGyCaUg3CGa
#    volumes:
#      - ~/mongodata:/data/db
#      - ~/backups/:/backups/
#    ports:
#      - 27017:27017


#  certbot:
#    image: certbot/certbot:latest
#    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email info@enforge.io --agree-tos --no-eff-email -d app.enforge.io
#    volumes:
#      - ~/certbot/conf/:/etc/letsencrypt
#      - ~/certbot/logs/:/var/log/letsencrypt
#      - ~/certbot/data:/usr/share/nginx/html/letsencrypt